version: "3.8"

services:
  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=major_tom
      - DOCKER_INFLUXDB_INIT_BUCKET=satellite_telemetry
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data: